# Generated by Django 3.2.5 on 2022-03-14 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.TextField(choices=[('Chinese', 'Chinese'), ('Indian', 'Indian'), ('Desserts', 'Desserts'), ('Japanese', 'Japanese'), ('Chat', 'Chat'), ('Drinks', 'Drinks')], default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='vegetarian',
            field=models.BooleanField(default=True),
        ),
    ]
