# Generated by Django 3.2.5 on 2022-03-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20220314_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=250)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Cart',
                'ordering': ['date_added'],
            },
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.TextField(choices=[('Chinese', 'Chinese'), ('Indian', 'Indian'), ('Desserts', 'Desserts'), ('Japanese', 'Japanese'), ('Chat', 'Chat'), ('Drinks', 'Drinks'), ('Fast Food', 'Fast Food')]),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.food')),
            ],
            options={
                'db_table': 'CartItem',
            },
        ),
    ]
