# Generated by Django 3.2.5 on 2022-03-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20220316_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
