# Generated by Django 3.2.5 on 2022-04-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
    ]
