# Generated by Django 3.2.5 on 2022-04-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20220429_1830'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table=None,
        ),
    ]
