# Generated by Django 3.2.5 on 2022-04-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_orderitem_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
