# Generated by Django 3.2.5 on 2022-04-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.CharField(default='.', max_length=400),
        ),
    ]
