# Generated by Django 3.2.5 on 2022-04-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_order_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='user_id',
            field=models.CharField(default='.', max_length=500),
        ),
    ]
