# Generated by Django 3.2.5 on 2022-04-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_orderitem_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='times_ordered',
            field=models.IntegerField(default=0),
        ),
    ]
