# Generated by Django 3.2.5 on 2022-04-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_food_times_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
